- name: variable in ansible
  hosts: mongodb
  # Here Dclaring variable at play level.
  vars:
    COURSE: DevOps
    TRAINER: Siva Kumar
    Duration: 110 hours
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, I am learnig Ansible"

  - name: printing variables
    ansible.builtin.debug:
      msg: "Hello, I am learnig {{COURSE}}, Trainer is {{TRAINER}}, Durations is {{Duration}}"