- name: variables form files
  hosts: localhost # local host nothing but managing the server itself.
  vars_files:
  - variable.yaml
  tasks:
  - name: Printing variables from file
    ansible.builtin.debug:
      msg: "We are learning {{NMAE}}, Duration is: {{DURATION}}, Trainer is {{TRAINER}}"