- name: Variables from Prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME # this is the variable name
    prompt: Please enter your username.
    private: false # this means we can see the value entered on screen 
  - name: PASSWORD
    prompt: Please enter your password
    private: true # here we can not see value entered on the screen

  tasks:
  - name: print variable values from prompt
    ansible.builtin.debug:
      msg: "Username: {{USERNAME}} and Password: {{PASSWORD}}"
  